name: Build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-nixos:
    name: Build NixOS hosts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build hosts
        run: |
          for host in $(nix eval --json --apply builtins.attrNames .#nixosConfigurations | jq -r '.[]'); do
            make build host="$host"
          done
