name: Build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  nixos:
    name: NixOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build hosts
        run: |
          for host in $(nix eval --json --apply builtins.attrNames .#nixosConfigurations | jq -r '.[]'); do
            nix build ".#nixosConfigurations.\"$host\".config.system.build.toplevel"
          done

  darwin:
    name: Darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build hosts
        run: |
          for host in $(nix eval --json --apply builtins.attrNames .#darwinConfigurations | jq -r '.[]'); do
            nix build ".#darwinConfigurations.\"$host\".system"
          done

      - name: Apply test config
        run: |
          sudo make host=macos-test
